export const easyOffsets = [
    { colOffset: 1, rowOffset: 0 },
    { colOffset: 1, rowOffset: -1 },
    { colOffset: 0, rowOffset: -1 },
    { colOffset: -1, rowOffset: -1 },
    { colOffset: -1, rowOffset: 0 },
    { colOffset: -1, rowOffset: 1 },
    { colOffset: 0, rowOffset: 1 },
    { colOffset: 1, rowOffset: 1 },
    { colOffset: 2, rowOffset: 0 },
    { colOffset: 2, rowOffset: 1 },
    { colOffset: 2, rowOffset: 2 },
    { colOffset: 1, rowOffset: 2 },
    { colOffset: 0, rowOffset: 2 },
    { colOffset: -2, rowOffset: 0 },
    { colOffset: -2, rowOffset: -1 },
    { colOffset: -2, rowOffset: -2 },
    { colOffset: -1, rowOffset: -2 },
    { colOffset: 0, rowOffset: -2 },
    { colOffset: -1, rowOffset: 2 }
]